### ISSUE TITLE
Errors found by the Locate mod errors function

### ISSUE THREAD

**Issue by nizhuan-jjr** [EmperorPinguin/3rd-and-4th-Unique-Component#14]
Arepa Power's unique "[+100]% Strength <when fighting in [Arepa House] tiles>" contains the conditional "when fighting in [Arepa House] tiles". This contains the parameter Arepa House which does not fit parameter type tileFilter !
Genoese Merchant's unique "Can construct [Customs house]" is deprecated as of 4.5.2, replace with "Can instantly construct a [Customs house] improvement <by consuming this unit>"
Daimyo's unique "Can start an [8]-turn golden age" is deprecated as of 4.5.3, replace with "Empire enters a [8]-turn Golden Age <by consuming this unit>"
Daimyo's unique "Can construct [Citadel]" is deprecated as of 4.5.2, replace with "Can instantly construct a [Citadel] improvement <by consuming this unit>"
Music Group's unique "Can start an [16]-turn golden age" is deprecated as of 4.5.3, replace with "Empire enters a [16]-turn Golden Age <by consuming this unit>"
Music Group's unique "Can construct [Landmark]" is deprecated as of 4.5.2, replace with "Can instantly construct a [Landmark] improvement <by consuming this unit>"
Cur's unique "Can start an [8]-turn golden age" is deprecated as of 4.5.3, replace with "Empire enters a [8]-turn Golden Age <by consuming this unit>"
Cur's unique "Can construct [Citadel]" is deprecated as of 4.5.2, replace with "Can instantly construct a [Citadel] improvement <by consuming this unit>"
Dalai Lama's unique "Can start an [10]-turn golden age" is deprecated as of 4.5.3, replace with "Empire enters a [10]-turn Golden Age <by consuming this unit>"
Dalai Lama's unique "Can construct [Holy site] <if it hasn't used other actions yet>" is deprecated as of 4.5.2, replace with "Can instantly construct a [Holy site] improvement <by consuming this unit>"
Induna's unique "Can start an [8]-turn golden age" is deprecated as of 4.5.3, replace with "Empire enters a [8]-turn Golden Age <by consuming this unit>"
Induna's unique "Can construct [Citadel]" is deprecated as of 4.5.2, replace with "Can instantly construct a [Citadel] improvement <by consuming this unit>"

![Screenshot_20230524_094601_com unciv app](https://github.com/DW8030/3rd-and-4th-Unique-Component/assets/3255986/832040bc-cc9f-47b4-88cc-14ee3345b34d)

**Comment by DW8030** [comment]
The mod is currently adding support for the Community civs mod, the red error is a result of that and will soon be fixed. I resolved the yellow errors.
