### ISSUE TITLE
A change to the Star Gazing Spot for VividVale.

### ISSUE THREAD

**Issue by BennieCUBED** [EmperorPinguin/3rd-and-4th-Unique-Component#42]
{
        "name": "Star Gazing Spot",
        "replaces": "Amphitheater",
            "uniqueTo": "VividVale",
        "culture": 2,
        "happiness": 2,
        "specialistSlots": {"Artist": 1},
        "requiredBuilding": "Monument",
        "maintenance": 1,
        "hurryCostModifier": 25,
        "uniques": ["[+2 Science] <after discovering [Astronomy]>","Destroyed when the city is captured"],
        "requiredTech": "Drama and Poetry"
    },

**Comment by EmperorPinguin** [comment]
Added
